name: Github Pages Deploy

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: develop
          folder: .
